# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'InMoovV1.0' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InMoovV1.0

pod 'ORSSerialPort', '2.0.2'

  target 'InMoovV1.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InMoovV1.0UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
